tunnel: "tunnel_id"
credentials-file: /etc/cloudflared/"tunnel_id".json


ingress:
  - hostname: nihon-go-up-app.omusubiy.com
    service: http://nihon-go-up-app-nginx:6000
    originRequest:
      noTLSVerify: true
  - service: http_status:404
  
