tunnel: "tunnel_id"
credentials-file: /etc/cloudflared/"tunnel_id".json


ingress:
  - hostname: "my-subdomain.com"
    service: http://nihon-go-up-app-nginx:6000
    no-tls-verify: true  # TLS検証をスキップ
  - service: http_status:404
  
