services:
  nihon-go-up-app-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nihon-go-up-app-backend
    working_dir: /backend
    volumes:
      - ./app:/backend/app
      - ./src:/backend/src
    ports:
      - "6000:6000" # ホストの port 8000 は別のサービスで使用しているため、6000 でアクセス
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 6000 --reload --forwarded-allow-ips="*"
    networks:
      - nihon-go-up-app_cloudflared_network
    depends_on:
      - nihon-go-up-app-cloudflared


  nihon-go-up-app-nginx:
    image: nginx:latest
    container_name: nihon-go-up-app-nginx
    ports:
      - "8081:6000"  # 外部からのアクセスは6000ポートを使用
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nihon-go-up-app-backend
    networks:
      - nihon-go-up-app_cloudflared_network

  nihon-go-up-app-cloudflared:
    build:
      context: .
      dockerfile: Dockerfile.cloudflared
    container_name: nihon-go-up-app-cloudflared
    networks:
      - nihon-go-up-app_cloudflared_network

networks:
  nihon-go-up-app_cloudflared_network:
    driver: bridge
